name: battleship
channels:
  - defaults
dependencies:
  - appdirs=1.4.4=py_0
  - astroid=2.4.2=py39haa95532_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - black=19.3b0=py_0
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=haa95532_0
  - certifi=2020.12.5=py39haa95532_0
  - click=7.1.2=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - icu=58.2=ha925a31_3
  - intel-openmp=2020.2=254
  - isort=5.6.4=py_0
  - jpeg=9b=hb83a4c4_2
  - lazy-object-proxy=1.4.3=py39h2bbff1b_2
  - libpng=1.6.37=h2a8f88b_0
  - mccabe=0.6.1=py39haa95532_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py39h196d8e1_0
  - mkl_fft=1.0.6=py39h054117c_0
  - mkl_random=1.0.2=py39h848d8c7_0
  - numpy=1.19.2=py39h729668d_0
  - numpy-base=1.19.2=py39hbd0edd7_0
  - openssl=1.1.1i=h2bbff1b_0
  - pip=20.3.3=py39haa95532_0
  - pylint=2.6.0=py39haa95532_0
  - pyqt=5.9.2=py39hd77b12b_6
  - python=3.9.1=h6244533_2
  - qt=5.9.7=vc14h73c81de_0
  - setuptools=52.0.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.15.0=py39haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - toml=0.10.1=py_0
  - tzdata=2020f=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - wrapt=1.11.2=py39h2bbff1b_0
  - zlib=1.2.11=h62dcd97_4
